# Menu config
# 菜单配置

[[main]]
  identifier = "Home"
  # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  pre = ""
  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  post = ""
  name = "Home"
  url = "/en/"
  # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
  title = "Home"
  weight = "1"
[[main]]
  identifier = "posts"
  # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  pre = ""
  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  post = ""
  name = "Blog"
  url = "/en/posts/"
  # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
  title = "All Article"
  weight = "2"
[[main]]
  identifier = "mastodon"
  pre = ""
  post = ""
  name = "Mastodon"
  url = "/mastodon/"
  title = "Mastodon Toots"
  weight = "3"
[[main]]
  identifier = "neodb"
  pre = ""
  post = ""
  name = "Media"
  url = "/media/"
  title = "NeoDB Movie TV Book Music Game"
  weight = "4"
[[main]]
  identifier = "steam"
  pre = ""
  post = ""
  name = "Steam"
  url = "/steam/"
  title = "Steam Games"
  weight = "5"
# [[main]]
#   identifier = "goods"
#   pre = ""
#   post = ""
#   name = "Goods"
#   url = "/goods/"
#   title = "Goods for a better life"
#   weight = "5"
# [[main]]
#   identifier = "categories"
#   pre = ""
#   post = ""
#   name = "Cates"
#   url = "/en/categories/"
#   title = "Categories"
#   weight = "6"
[[main]]
  identifier = "links"
  name="Friends"
  pre = ""
  post = ""
  url="/links/"
  title = "Friends links"
  weight="7"
[[main]]
  identifier = "stats"
  name="Stats"
  pre = ""
  post = ""
  url="/stats/"
  title = "Stats"
  weight="9"
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = "About me"
  weight = "99"
# [[main]]
#   identifier = "Mastodon"
#   pre = ""
#   post = "<span class='menu-item-nav'>Mastodon</span>"
#   name=""
#   url="https://e5n.cc/@eallion"
#   title = "Mastodon e5n.cc"
#   weight="9"
