# Menu config
# 菜单配置

[[main]]
  identifier = "Home"
  # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  pre = "<i class='fas fa-home'></i>"
  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  post = ""
  name = "Home"
  url = "/en/"
  # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
  title = "Home"
  weight = "1"
[[main]]
  identifier = "posts"
  # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  pre = "<i class='fas fa-blog'></i>"
  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  post = ""
  name = "Blog"
  url = "/en/posts/"
  # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
  title = "All Article"
  weight = "2"
[[main]]
  identifier = "toots"
  pre = "<i class='fab fa-mastodon'></i>"
  post = ""
  name = "Toots"
  url = "/toot/"
  title = "Toots"
  weight = "3"
[[main]]
  identifier = "movie"
  pre = "<i class='fas fa-film'></i>"
  post = ""
  name = "Watched"
  url = "/movie/"
  title = "DouBan Movie"
  weight = "4"
# [[main]]
#   identifier = "goods"
#   pre = "<i class='fas fa-gift'></i>"
#   post = ""
#   name = "Goods"
#   url = "/goods/"
#   title = "Goods for a better life"
#   weight = "5"
# [[main]]
#   identifier = "categories"
#   pre = "<i class='fas fa-stream'></i>"
#   post = ""
#   name = "Cates"
#   url = "/en/categories/"
#   title = "Categories"
#   weight = "6"
[[main]]
  identifier = "links"
  name="Friends"
  pre = "<i class='fas fa-users'></i>"
  post = ""
  url="/links/"
  title = "Friends links"
  weight="7"
[[main]]
  identifier = "about"
  pre = "<i class='fas fa-info'></i>"
  post = ""
  name = "About"
  url = "/about/"
  title = "About me"
  weight = "99"
# [[main]]
#   identifier = "Mastodon"
#   pre = "<i class='fab fa-mastodon'></i>"
#   post = "<span class='menu-item-nav'>Mastodon</span>"
#   name=""
#   url="https://e5n.cc/@eallion"
#   title = "Mastodon e5n.cc"
#   weight="9"
