# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo --cleanDestinationDir --forceSyncStatic --gc --ignoreCache --minify
  except:
  - main

pages:
  script:
  - hugo --cleanDestinationDir --forceSyncStatic --gc --ignoreCache --minify
  artifacts:
    paths:
    - public
  only:
  - main
