baseURL  =  "https://eallion.com"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title  =  "大大的小蜗牛"
subtitle = "机会总是垂青于有准备的人"
keywords = "蜗牛,大大的小蜗牛,eallion,snail,woniu,博客,代码,运营,电子商务,电商,嘀咕,hugo,code"
description = "A blog about Charles 'eallion' Chin. 大大的小蜗牛的个人博客。"
author = "Charles Chin"
timezone = "Asia/Shanghai"
theme  =  "hello-friend"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 10
# uglyurls = true

[permalinks]
  posts = "/:slug/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
  name="嘀咕"
  url="https://eallion.com/talk/"
  weight="1"
  #[[menu.main]]
  #name="观影"
  #url="/movies/"
  #weight="2"
  #[[menu.main]]
  #name="相册"
  #url="/photos/"
  #weight="3"
  [[menu.main]]
  name="归档"
  url="https://eallion.com/archives/"
  weight="4"
  [[menu.main]]
  name="友链"
  url="https://eallion.com/links/"
  weight="5"
  [[menu.main]]
  name="关于"
  url="https://eallion.com/about/"
  weight="6"
  [[menu.main]]
  name="日志"
  url="https://eallion.com/posts/daily/"
  weight="11"
  [[menu.main]]
  name="代码"
  url="https://eallion.com/posts/code/"
  weight="12"
  [[menu.main]]
  name="运营"
  url="https://eallion.com/posts/operation/"
  weight="13"
  [[menu.main]]
  name="分享"
  url="https://eallion.com/posts/share/"
  weight="14"
  [[menu.main]]
  name="山贼"
  url="https://eallion.com/posts/sz/"
  weight="15"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  minuteReadingTime = "分钟阅读"
  logoText = "hello friend"
  logoHomeLink = "/"

  MenuMore = "分类"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/eallion/eallion.com/edit/main/content'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML", "JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.waline]
  enable = true
  placeholder = "说点什么吧……"
  serverURL = "https://eallion-160d1d-1251347414.ap-shanghai.app.tcloudbase.com/waline"
  requiredFields = "['nick','mail']"
  emojiCDN = "//i0.hdslb.com/bfs/emote/"
  avatarCDN = "https://dn-qiniu-avatar.qbox.me/avatar/"

[params.MiniValine]
  enable = false
  backend = "waline"
  placeholder = "说点什么吧……"
  serverURLs = "https://eallion-160d1d-1251347414.ap-shanghai.app.tcloudbase.com/waline"
  requiredFields = "['nick','mail']"
  avatarCDN = "https://dn-qiniu-avatar.qbox.me/avatar/"
  mode = "xCss"

[params.twikoo]
  enable = false

[params.comment.disqus]
  enable = false
  proxy = "true"
  shortname = "eallion"
  api =  "https://disqus.skk.moe/disqus/"
  apikey = "fF9m3DwDSmNQ2g5DIpuWElDaQTx1ofpMSSW8JeKaB2loVBExeInmMbaEGeLs7lOL"
  admin = "eallion"
  adminLabel = ""
  nocomment = ""

[params.comment.utterances]
  enable = false
  repo="eallion/blog"
  issueterm="url"
  label="Comments"
  theme="github-light"