baseURL  =  "https://eallion.com"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title  =  "大大的小蜗牛"
theme  =  "hello-friend"
timeZone = "Asia/Shanghai"
hasCJKLanguage = true
summaryLength = 226
# 每页显示的文章数量用于分页
paginate = 8
# rss 输出数量
rssLimit = 10
rssFullText = true
rssImage = ""
# uglyurls = true

enableEmoji = true
enableGitInfo = false

[permalinks]
  posts = "/:slug/" # Don't miss the last slash: "/"
  tags = "/tags/:slug/" # Don't miss the last slash: "/"

[params]
  # copyright = ""
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  minuteReadingTime = "分钟阅读"
  # lastModDisplay = "更新："
  logoText = "hello friend"
  logoHomeLink = "/"

  MenuMore = "更多"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  title  =  "大大的小蜗牛"
  subtitle = "机会总是垂青于有准备的人"
  keywords = "蜗牛,大大的小蜗牛,eallion,snail,woniu,Charles,Chin,博客,静态博客,电商,代码,运营,电子商务,电商,嘀咕,hugo,code"
  description = "A blog about Charles eallion Chin. 大大的小蜗牛的个人博客。—— 机会总是垂青于有准备的人"
  author = "Charles Chin"
  theme  =  "hello-friend"

  GitRepo = "https://github.com/eallion/eallion.com"
  Commit = "https://github.com/eallion/eallion.com/tree/" # Don't miss the last slash: "/"
  LastCommitHash = "69d6ffe319557706dcf4150e960e7b7e21a37d9f" # see ./githash.sh
  EditPath = 'https://github.com/eallion/eallion.com/edit/main/content/' # Don't miss the last slash: "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = false

[outputs]
  home = ["Atom", "HTML", "JSON", "AMP",]
  page = ["HTML"]

[outputFormats.Atom] # <domain>/atom.xml
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.AMP]
  mediaType = "text/html"
  isPlainText = false
  isHTML = true

[params.mdview] # View original markdown of post on GitHub
  enable = true
  ContentPath = 'https://raw.githubusercontent.com/eallion/eallion.com/main/content/' # Don't miss the last slash: "/"
  #ContentPath = 'https://git.eallion.com/eallion/eallion.com/raw/branch/main/content/' # Don't miss the last slash: "/"
  #ContentPath = 'https://eallion.coding.net/p/eallion/d/hugo/git/raw/main/content/' # Don't miss the last slash: "/"

[params.disqus]
  enable = true
  version = "1.3.0"

[menu]
  ## main menu
  [[menu.main]]
  name="嘀咕"
  url="/talks/" # Don't miss the last slash: "/"
  weight="1"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="2"
  [[menu.main]]
  name="友链"
  url="/links/"
  weight="3"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="4"
  ## more menu
  #[[menu.main]]
  #name="日记"
  #url="/posts/daily/"
  #weight="11"
  ## external menu
  [[menu.main]]
  name="版权"
  url="/copyright/"
  weight="21"
  [[menu.main]]
  name="隐私"
  url="/privacy-policy/"
  weight="22"
  [[menu.main]]
  name="RSS"
  url="/atom.xml"
  weight="23"
