baseURL  =  "https://eallion.com"
languageCode = "zh-CN"
DefaultContentLanguage = "zh-CN"
title  =  "大大的小蜗牛"
subtitle = "机会总是垂青于有准备的人"
keywords = "蜗牛,大大的小蜗牛,eallion,snail,woniu,博客,代码,运营,电商,嘀咕,hugo,code"

theme  =  "hello-friend"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  20
# rss 输出数量
rssLimit = 10

[permalinks]
  posts = "/:slug/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
  name="嘀咕"
  url="/talk/"
  weight="1"
  [[menu.main]]
  name="观影"
  url="/movies/"
  weight="2"
  #[[menu.main]]
  #name="相册"
  #url="/photos/"
  #weight="3"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="4"
  [[menu.main]]
  name="友链"
  url="/links/"
  weight="5"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="6"
  [[menu.main]]
  name="日 志"
  url="/posts/daily/"
  weight="11"
  [[menu.main]]
  name="代 码"
  url="/posts/code/"
  weight="12"
  [[menu.main]]
  name="运 营"
  url="/posts/operation/"
  weight="13"
  [[menu.main]]
  name="分 享"
  url="/posts/share/"
  weight="14"
  [[menu.main]]
  name="山 贼"
  url="/posts/sz/"
  weight="15"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  logoText = "hello friend"
  logoHomeLink = "/"

  MenuMore = "分类"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/eallion/hugo/edit/master/content'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.valine]
  enable = false
  appId = '8BvPJ6EeOAkQ4AFttNyYEfET-9Nh9j0Va'
  appKey = 'FGQItPQDpoTal7yzzETx5vnK'
  placeholder = '说点什么吧……'
  visitor = true

[params.comment.disqus]
  enable = "true"
  proxy = "true"
  shortname = "eallion"
  api =  "https://disqus.skk.moe/disqus/"
  apikey = "fF9m3DwDSmNQ2g5DIpuWElDaQTx1ofpMSSW8JeKaB2loVBExeInmMbaEGeLs7lOL"
  admin = "eallion"
  adminLabel = ""