baseURL  =  "https://eallion.com"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title  =  "大大的小蜗牛"
theme  =  "hello-friend"
timezone = "Asia/Shanghai"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 10
# uglyurls = true

[permalinks]
  posts = "/:slug/"
  tags = "/tags/:slug/"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  minuteReadingTime = "分钟阅读"
  # lastModDisplay = "更新："
  logoText = "hello friend"
  logoHomeLink = "/"

  MenuMore = "更多"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/eallion/eallion.com/edit/main/content'
  
  title  =  "大大的小蜗牛"
  subtitle = "机会总是垂青于有准备的人"
  keywords = "蜗牛,大大的小蜗牛,eallion,snail,woniu,Charles,Chin,博客,静态博客,电商,代码,运营,电子商务,电商,嘀咕,hugo,code"
  description = "A blog about Charles eallion Chin. 大大的小蜗牛的个人博客。—— 机会总是垂青于有准备的人"
  author = "Charles Chin"
  theme  =  "hello-friend"

[menu]
  ## main menu
  [[menu.main]]
  name="嘀咕"
  url="https://eallion.com/talk/"
  weight="1"
  [[menu.main]]
  name="归档"
  url="https://eallion.com/archives/"
  weight="2"
  [[menu.main]]
  name="友链"
  url="https://eallion.com/links/"
  weight="3"
  [[menu.main]]
  name="关于"
  url="https://eallion.com/about/"
  weight="4"

  ## sub menu
  [[menu.main]]
  name="观影"
  url="https://eallion.com/movies/"
  weight="11"
  [[menu.main]]
  name="阅读"
  url="https://eallion.com/books/"
  weight="12"
  #[[menu.main]]
  #name="相册"
  #url="/photos/"
  #weight="13"

  ## more menu
  [[menu.main]]
  name="日记"
  url="https://eallion.com/posts/daily/"
  weight="21"
  #[[menu.main]]
  #name="代码"
  #url="https://eallion.com/posts/code/"
  #weight="22"
  #[[menu.main]]
  #name="运营"
  #url="https://eallion.com/posts/operation/"
  #weight="23"
  #[[menu.main]]
  #name="分享"
  #url="https://eallion.com/posts/share/"
  #weight="24"
  #[[menu.main]]
  #name="山贼"
  #url="https://eallion.com/posts/sz/"
  #weight="25"

  ## external menu
  [[menu.main]]
  name="导航"
  url="https://s.eallion.com/"
  weight="31"
  [[menu.main]]
  name="版权"
  url="https://eallion.com/copyright/"
  weight="32"
  [[menu.main]]
  name="隐私"
  url="https://eallion.com/privacy-policy/"
  weight="33"
  [[menu.main]]
  name="订阅"
  url="https://eallion.com/atom.xml"
  weight="34"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML", "JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.waline]
  enable = false
  version = '1.3.1'

[params.twikoo]
  enable = true
  version = '1.3.1'

[params.disqus]
  enable = false
  version = '1.3'

[params.utterances]
  enable = false

[params.noticeable]
  enable = false
  id = "a0yLJIkjSFFgsQ1IIqT8"
