# .github/workflows/douban.yml
name: Sync Douban Data
on:
  schedule:
  - cron: "0 */12 * * *"
#  watch:
#    types: [started]

  workflow_dispatch:
  repository_dispatch:

jobs:
  douban:
    name: Douban Data Sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Fetch Movie Data JSON
      uses: lizheming/doumark-action@master
      with:
        id: eallion
        type: movie
        format: json
        dir: ./data/douban

    - name: Sync to NeoDB
      uses: lizheming/doumark-action@master
      with:
        id: eallion
        type: movie
        format: neodb
        neodb_token: ${{ secrets.NEODB_ACCESS_TOKEN }}

    - name: Sync Movie to Notion
      uses: lizheming/doumark-action@master
      with:
        id: eallion
        type: movie
        format: notion
        dir: ${{ secrets.NOTION_MOVIE_ID }}
        notion_token: ${{ secrets.NOTION_ACCESS_TOKEN }}

    - name: Fetch Book Data JSON
      uses: lizheming/doumark-action@master
      with:
        id: eallion
        type: book
        format: json
        dir: ./data/douban

    - name: Sync Book to NeoDB
      uses: lizheming/doumark-action@master
      with:
        id: eallion
        type: book
        format: neodb
        neodb_token: ${{ secrets.NEODB_ACCESS_TOKEN }}

    - name: Sync Book to Notion
      uses: lizheming/doumark-action@master
      with:
        id: eallion
        type: movie
        format: notion
        dir: ${{ secrets.NOTION_BOOK_ID }}
        notion_token: ${{ secrets.NOTION_ACCESS_TOKEN }}

    - name: Git Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore(data): update douban data'
        add: './data/douban'
