name: Upload GTS to Algolia

on:
#  push:
#    branches:
#      - main
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Fetch Memos JSON
        run: |
          data_url="https://api.eallion.com/gotosocial/api/v1/accounts/01RVAVVGAPXR989VKK1BQV6BFS/statuses?limit=10"
          output_file="output.json"
          curl -s "$data_url" | jq '.[] | {objectID:  (.id | tostring), date: .created_at, content: (.content | gsub("<[^>]*>";"")), uri, title: (.content | gsub("<[^>]*>";"") | rtrimstr("\n") | .[ :20])}' > "$output_file"
          jq -s '.' "$output_file" > gotosocial.json

      - name: Algolia uploader
        uses: wangchucheng/algolia-uploader@master
        with:
          app_id: ${{ secrets.ALGOLIA_APPID }}
          admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          index_name: gotosocial
          index_file_path: gotosocial.json
