name: Deploy Hugo

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
       # with:
       #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.67.1
          # latest
          # extended: true

      - name: Build
        run: hugo

      - name: Deploy to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
          commit_message: ${{ github.event.head_commit.message }}
      
      # 部署到腾宝塔服务器
      #- name: Webhook
      #  uses: distributhor/workflow-webhook@v1
      #  env:
      #    webhook_url: ${{ secrets.WEBHOOK_URL }}
      #    webhook_secret: ${{ secrets.WEBHOOK_SECRET }}

      # 部署到阿里云
      - name: Setup OSS
        uses: manyuanrong/setup-ossutil@v1.0
        with:
        # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-shanghai.aliyuncs.com"
        # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      - name: Deply To OSS
        run: ossutil cp public oss://eallion-test/ -rf