name: Deploy Hugo

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
       # with:
       #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.67.1
          # latest
          # extended: true

      - name: Build Hugo
        run: hugo --cleanDestinationDir --forceSyncStatic --gc --ignoreCache --minify

      - name: Deploy to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          PUBLISH_BRANCH: public
          PUBLISH_DIR: ./public
          commit_message: ${{ github.event.head_commit.message }}
      
      # 部署到腾宝塔服务器
      #- name: Webhook
      #  uses: distributhor/workflow-webhook@v1
      #  env:
      #    webhook_url: ${{ secrets.WEBHOOK_URL }}
      #    webhook_secret: ${{ secrets.WEBHOOK_SECRET }}

      # 部署到阿里云 OSS 脚本1
      #- name: Setup OSS
      #  uses: manyuanrong/setup-ossutil@v1.0
      #  with:
      #    endpoint: "oss-accelerate.aliyuncs.com"
      #    access-key-id: ${{ secrets.ACCESS_KEY_ID }}
      #    access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      #- name: Deply To OSS
      #  run: ossutil cp public oss://eallion-com/ -rf

      # 部署前删掉一些无用文件
      - name: Delete images
        run: |
          cd public
          rm -rf images
          cd ..

      # 部署到阿里云 OSS 脚本2
      - name: Deploy to OSS
        uses: saltbo/uptoc@master
        with:
          driver: oss
          region: oss-cn-shanghai
          bucket: eallion-com
          dist: public
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.ACCESS_KEY_ID }}
          UPTOC_UPLOADER_SK: ${{ secrets.ACCESS_KEY_SECRET }}